config/routes.rb
Rails.application.routes.draw do
  resources :gifs
  resources :searches

  root to: 'gifs#index'

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :gifs
  has_many :tags, through: :gifs
end

app/models/gif.rb
class Gif < ActiveRecord::Base
  belongs_to :board
  has_many :tags
end

app/models/giphy.rb
class Giphy 
  attr_reader :query, :url

  def initialize(query)
    @query = query
    @url = "http://api.giphy.com/v1/gifs/search?q=#{@query}&api_key=dc6zaTOxFJmzC&limit=20"
  end

  def search
    doc = Nokogiri::HTML(open(url))
    json = JSON.parse(doc)

    results = json["data"].collect do |data|
      {rating: data["rating"], name: data["id"], url: data["images"]["fixed_width"]["url"]}
    end
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :gif
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController

  def index
    @gifs = Gif.all
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    
  end

  def create
    @search_results = Giphy.new(params[:q]).search

    respond_to do |format|
      format.html {redirect_to searches_path}
      format.js {}
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gifs_helper.rb
module GifsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/gifs/_gif.html.erb
<div class="col-md-3">
  <img src="<%= gif.url %>" width="150" height="150"> <br>
  name: <%= gif.name %> <br>
  rating: <%= gif.rating %>
</div>

app/views/gifs/index.html.erb
<div class="page-header">
  <h1>Gifs</h1>
  <%= render @gifs %>
</div>

app/views/gifs/search.html.erb
<div class="page-header">
  <h1>Search</h1>
</div>
<div class="row">
  <div class="col-md-6">
  <%= form_tag("/search", method: "get", class:"form-horizontal") do |q| %>
    <div class="form-group">
      <%= label_tag(:q, "Search for a gif from giphy") %>
      <%= text_field_tag(:q, "", class: "form-control") %>      
    </div>
    <div class="form-group">
      <%= submit_tag("Search", class: "btn btn-default", remote: true) %>      
    </div>
  <% end %>
  </div>
</div>

app/views/layouts/_nav.html.erb
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Gif Graph</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to("Gifs", gifs_path , id: "gifs") %></li>
            <li><a href="#about">Boards</a></li>
            <li><a href="#contact">Tags</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GifGraph</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/nav' %>
  <div class="container container-body">
    <%= yield %>  
  </div>


</body>
</html>

app/views/layouts/nav.html.erb
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Gif Graph</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Gifs</a></li>
            <li><a href="#about">Boards</a></li>
            <li><a href="#contact">Tags</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/searches/_search_results.html.erb
<div class="row search-results">
  <% if @search_results %>
    <% @search_results.each do |result| %>
      <div class="col-md-4">
        <img src="<%= result[:url] %>" height="200" > <br>
        <%= result[:name] %> <br>
        <%= result[:rating] %> <br>
      </div>
    <% end %>
  <% end %>
</div>

app/views/searches/create.js.erb
$('.search-results').html('<%= j render "search_results" %>');

app/views/searches/index.html.erb
<div class="page-header">
  <h1>Search</h1>
</div>
<div class="row">
  <div class="col-md-6">
  <%= form_tag("/searches", method: "post", remote: true) do %>
    <%= label_tag(:q, "Search for:") %>
    <%= text_field_tag(:q) %>
    <%= submit_tag "Search", remote: true%>
  <% end %>
  </div>
</div>
<%= render 'search_results' %>